language: python
python: 3.6
addons:
  apt_packages:
    - pandoc
install: pip install -r docs/requirements.txt

# https://github.com/drdoctr/doctr
sudo: false
env:
  global:
    secure: "PWE4ekUYFiGg8coD43OPs4rP30oH+03ayJc8blyTZc2UfLETzy3hQINvM+piz7y6pdptJ9r8GyHW+j4MdXYWb98O2H/ZgI4TeLXCacvltfQR+65kJeVWRNrNchnSzbwC8w8deIB3IvIOmZxuTsw2FfKA/ZY9bmI9ZvS+1wvQIOx8J4QGZN+zWUHdanonTlJMreiKjzO0a7YZTHRVqZhSDtyzimEiALF5SQ1cwKQqwCcX1Pwz3kM6xjE6GZODbx25YMvtZg0YrJtrs1zji1PeXvZ39A2XfcX33ARNCz+jpESs174sHlj9YV/GRqYFy5JoEmsnPD2RYclclC9scinsiw6Ki8RZUbclKsceMDDIcKzeh184cJKF7uLoM0bcvbeULRFJKsfPgjD2dAVt8iCbPvzPVE32Gc5AhN0flLmVjmsiBENSKPlbZBg3TPhzuLMdG/sahVwatf531qSd7XMB/2AwPBExjnaONm78vyxKoB9SRxur/PevICwBc3+3UKE/ev3ZN6ow/DqwzLa34ayxH6Yero8/Yfw+aLQGYWC7yt4nC0rYpChnDjXSpegM9pedW2E3brCpu97fMDAktjmZHone3VfnYNOwdZw3r5JNQfPWZIeKRTPfwP3Xj3Rnwc7j7E92FVnmZjo7G2hnBJ6anTahQs/6UAbj6bZqJtlqFHc="

script:
  - set -e
  - cd docs && make html && cd ..
  - doctr deploy . --built-docs docs/_build/html
